minio:
  endpoint: ${MINIO_ENDPOINT:http://minio:9000}
  root_user: ${MINIO_ROOT_USER:my-key}
  root_password: ${MINIO_ROOT_PASSWORD:my-password-key}
  bucket: ${MINIO_BUCKET:conversions}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8081/eureka/}

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS:kafka:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: spring_micro.pdf_converter.event

server:
  port: 8083